### ISSUE TITLE
about Tutorial2

### ISSUE THREAD

**Issue by faker09** [AntonioLonga/AdvancePyTorchGeometricTutorials#1]
when i installed PyG 2.0 and move the graphgym code to my host,  whether i can directly run run_single.sh？  truthly,  when i finished these step, i can not run run_single.sh

**Comment by GabrieleSantin** [comment]
Hi and welcome! Can you give us some more detail? What kind of error message do you get?

**Comment by faker09** [comment]
i find a datasets file on graphgym fold on your video, but i have not it ,  the version of official release alsi have not
===>(https://github.com/pyg-team/pytorch_geometric/tree/master/graphgym)

this is my error message

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
```

**Comment by faker09** [comment]
i find a difference between the graphgym fold like your represent on video and my graphgym fold.
you have a datasets file on graphgym fold , but i have not , the version of official released also.
look here(https://github.com/pyg-team/pytorch_geometric/tree/master/graphgym)
i don't know whether it is reason

this is my error message
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
```

**Comment by GabrieleSantin** [comment]
Hi, the error seems to be related to the new decorator  @register_config, which was added in a commit 3 days ago. I did not had a look into it yet. Maybe you can try to checkout an older commit and see if it works?

**Comment by faker09** [comment]
i try to back the older commit. it does not working.

**Comment by GabrieleSantin** [comment]
Do you get the same error?

**Comment by faker09** [comment]
this is commit-ID  ==>5b4ccafa1409aa4711c0f11713ad53cc79806383
and this is error message
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
```
if we back the more old commits, the error message is different

**Comment by GabrieleSantin** [comment]
Can you give me the error message that you get with the old commit?

**Comment by faker09** [comment]
this is commit id   ==> 20cb2ed89a128119924fdd1f90ff0f57e34b68ce

and this is different error message
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 3, in <module>
    from .encoder import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\encoder\example.py", line 5, in <module>
    from ogb.utils.features import get_bond_feature_dims
ModuleNotFoundError: No module named 'ogb'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 3, in <module>
    from .encoder import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\encoder\example.py", line 5, in <module>
    from ogb.utils.features import get_bond_feature_dims
ModuleNotFoundError: No module named 'ogb'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 3, in <module>
    from .encoder import * # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\encoder\example.py", line 5, in <module>
    from ogb.utils.features import get_bond_feature_dims
ModuleNotFoundError: No module named 'ogb'

```

**Comment by faker09** [comment]
which commit ID do you used in video?

**Comment by GabrieleSantin** [comment]
This one: https://github.com/pyg-team/pytorch_geometric/commit/5f8e99d033a596426ef502c2ea4b9be89ec58f38
In your last error message, it looks like you are missing ogb. You can get e.g. via conda https://anaconda.org/conda-forge/ogb

**Comment by faker09** [comment]
truthly , it does not working. now i make up to  date. there are the message error.  hope you can help me.
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import *  # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import *  # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import custom_graphgym  # noqa, register custom modules
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\__init__.py", line 2, in <module>
    from .config import *  # noqa
  File "C:\Users\admin\pytorch_geometric\graphgym\custom_graphgym\config\example.py", line 6, in <module>
    @register_config('example')
TypeError: register_config() missing 1 required positional argument: 'module'
```
